### ISSUE TITLE
recursion error trying to run the tb

### ISSUE THREAD

**Issue by mattvenn** [ylm/nibblecpu#2]
```
Traceback (most recent call last):
  File "tb_smolcpu.py", line 28, in <module>
    sim = Simulator(dut)
  File "/home/matt/.local/lib/python3.8/site-packages/amaranth/sim/core.py", line 68, in __init__
    self._engine   = engine(self._fragment)
  File "/home/matt/.local/lib/python3.8/site-packages/amaranth/sim/pysim.py", line 282, in __init__
    self._processes = _FragmentCompiler(self._state)(self._fragment)
  File "/home/matt/.local/lib/python3.8/site-packages/amaranth/sim/_pyrtl.py", line 463, in __call__
    processes.update(self(subfragment))
  File "/home/matt/.local/lib/python3.8/site-packages/amaranth/sim/_pyrtl.py", line 455, in __call__
    exec(compile(code, filename, "exec"), exec_locals)
RecursionError: maximum recursion depth exceeded during compilation
```

**Comment by ylm** [comment]
This is likely Python/platform related. As per [Python documentation](https://docs.python.org/3/library/sys.html#sys.setrecursionlimit), the recursion limit is platform dependant. My recursion limit is set to 1000 on my platform and its works quite well.
But looking at the call stack, it doesn't look all that deep, so I wonder if there's anything else at play here.
